services:
  map-uploader:
    build: .
    environment:
      # Set to the appropriate device for your setup, either /dev/ttyACM0 if connected by USB to a USB companion or IP:port if connected over network to a wifi companion
      - DEVICE=10.0.1.4:5000
    restart: unless-stopped
    # Only necessary for accessing USB devices, such as a USB companion
    privileged: false